<?php

?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>" style="display: none">
    <div class="admin__field _required">
        <label for="phone_number" class="admin__field-label"><span><?= $block->escapeHtml(__('Phone number')) ?></span></label>
        <div class="admin__field-control">
            <input type="text" id="phone_number" name="payment[phone_number]"
                   title="<?= $block->escapeHtml(__("Phone number")) ?>" class="required-entry admin__control-text"
                   value="<?= /* @noEscape */ $block->getInfoData('phone_number') ?>"/>
        </div>
    </div>
</fieldset>